### ISSUE TITLE
Steps documentation and code don't match

### ISSUE THREAD

**Issue by ludicruz** [derptest/phpmachinst-behat-extension#1]
from "behat -dl"
Given /^the following "(?P<blueprint>(?:[^"]|\")_)" data exists:$/
Given /^I wipe all "(?P<blueprint>(?:[^"]|\")_)" data$/
Given /^I wipe all data$/
 Then /^there is no "(?P<blueprint>(?:[^"]|\")_)" data$/
 Then /^the following "(?P<blueprint>(?:[^"]|\")_)" data is found:$/
 Then /^only the following "(?P<blueprint>(?:[^"]|\")*)" data is found:$/

**Comment by aenglander** [comment]
Updated documentation
