### ISSUE TITLE
Bug: The Special Values In Steps Capability Is Broken

### ISSUE THREAD

**Issue by albertnelsen** [derptest/phpmachinst-behat-extension#2]
According to the 5th section of the manual, "Use the included steps:", you should be able to use {null} to get a null value inserted into a table, along with {false} for false values and {true} for true values but this is not working.  These values just get treated as text like everything else.

**Comment by aenglander** [comment]
This was left out of the original development.  Fix will be forthcoming this weekend.

**Comment by aenglander** [comment]
This is resolved in the v2.0.0-beta1 release
