### ISSUE TITLE
Using "the following <blueprint> data is found" throws exception when <blueprint> has a relationship

### ISSUE THREAD

**Issue by albertnelsen** [derptest/phpmachinst-behat-extension#3]
The error message produced is "Catchable Fatal Error: Object of class DerpTest\Machinist\Machine could not be converted to string".

The problem seems to be that when the theFollowingDataIsFound() function is preparing the search data, it creates a machine to represent the related table data, and adds the machine to the list of data to search on.  None of the functions that follow know what to do with the machine object in this list and eventually an attempt is made to convert it to a string and this throws the exception.

**Comment by aenglander** [comment]
This is resolved in the v2.0.0-beta1 release
